Debugging imgui building and locations

diff --git a/.github/workflows/android-build.yml b/.github/workflows/android-build.yml
--- a/.github/workflows/android-build.yml
+++ b/.github/workflows/android-build.yml
@@ -72,38 +72,45 @@ jobs:
           
           ./gradlew :imgui-binding:generateLibs -Denvs=android -Dlocal -Dtarget=all -PandroidNdkPath=$ANDROID_NDK_HOME -PandroidAbi=arm64-v8a
           
-          MK_FILE=$(find . -name "Android.mk" | head -n 1)
+          echo "--- FILES, imgui-binding/build -L 4 ---"
+          tree imgui-binding/build -L 4
           
-          if [ -z "$MK_FILE" ]; then
-            echo "Android.mk not found, trying fallback"
-            MK_FILE=$(find imgui-binding/build -name "Android.mk" | head -n 1)
-          fi
+          echo "--- SEARCH .mk ---"
+          find . -name "*.mk"
+          
+          MK_PATH=$(find . -name "Android.mk" | head -n 1)
 
-          if [ -z "$MK_FILE" ]; then
+          echo "--- ALL FILES ---"
+          tree -L 5
+          echo "--- ALL FILES ---"
+          
+          if [ -z "$MK_PATH" ]; then
             echo "Android.mk not found"
+            tree imgui-binding/src/main/cpp
             exit 1
           fi
-
-          tree . -L 4
           
-          JNI_DIR=$(dirname "$MK_FILE")
-          echo "found Android.mk at: $JNI_DIR"
+          JNI_DIR=$(dirname "$MK_PATH")
+          echo "found Android.mk at $JNI_DIR"
           
           $ANDROID_NDK_HOME/ndk-build -C "$JNI_DIR" \
-            NDK_PROJECT_PATH="." \
-            APP_BUILD_SCRIPT="Android.mk" \
+            NDK_PROJECT_PATH=. \
+            APP_BUILD_SCRIPT=Android.mk \
             APP_ABI=arm64-v8a \
             APP_PLATFORM=android-24
           
           mkdir -p $GITHUB_WORKSPACE/imgui-native-android
+          
           IMGUI_SO=$(find . -name "libimgui-java.so" | grep "arm64-v8a" | head -n 1)
           
           if [ -z "$IMGUI_SO" ]; then
-             IMGUI_SO=$(find . -name "libimgui-java*.so" | grep "arm64-v8a" | head -n 1)
+            echo "imgui not found"
+            find . -name "*.so"
+            exit 1
           fi
 
           cp "$IMGUI_SO" $GITHUB_WORKSPACE/imgui-native-android/libimgui-java64.so
-          echo "--- SUCCESS ---"
+          echo "SUCCESS, imgui at $GITHUB_WORKSPACE/imgui-native-android/libimgui-java64.so"
           
       - name: build rapier (rust natives)
         run: |
