Debugging imgui location and ndk building it, on build

diff --git a/.github/workflows/android-build.yml b/.github/workflows/android-build.yml
--- a/.github/workflows/android-build.yml
+++ b/.github/workflows/android-build.yml
@@ -65,7 +65,7 @@ jobs:
 
       - name: build imgui
         run: |
-          sudo apt-get update && sudo apt-get install -y ant
+          sudo apt-get update && sudo apt-get install -y ant tree
           git clone --depth 1 https://github.com/SpaiR/imgui-java.git
           cd imgui-java
           chmod +x ./gradlew
@@ -73,20 +73,29 @@ jobs:
           ./gradlew :imgui-binding:generateLibs -Denvs=android -Dlocal -Dtarget=all -PandroidNdkPath=$ANDROID_NDK_HOME -PandroidAbi=arm64-v8a
           
           cd imgui-binding/build/jni
-          ant clean
-          ant -Denvs=android -Dndk.path=$ANDROID_NDK_HOME -Dabi=arm64-v8a compile-natives
           
-          IMGUI_SO=$(find ../libsNative/android/arm64-v8a -name "*.so" | head -n 1)
+          $ANDROID_NDK_HOME/ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./Android.mk APP_ABI=arm64-v8a APP_PLATFORM=android-24
           
+          echo "--- FILES ---"
+          cd ../..
+          tree build/libsNative || ls -R build/libsNative || echo "directory not found"
+
+          mkdir -p $GITHUB_WORKSPACE/imgui-native-android
+          
+          IMGUI_SO=$(find . -name "libimgui-java.so" | grep "arm64-v8a" | head -n 1)
+          
+          if [ -z "$IMGUI_SO" ]; then
+            IMGUI_SO=$(find . -name "libimgui-java64.so" | grep "arm64-v8a" | head -n 1)
+          fi
+
           if [ -z "$IMGUI_SO" ]; then
             echo "imgui not found"
             exit 1
           fi
 
-          mkdir -p $GITHUB_WORKSPACE/imgui-native-android
-          echo "found imgui at $IMGUI_SO"
+          echo "SUCCESS, imgui at $IMGUI_SO"
           cp "$IMGUI_SO" $GITHUB_WORKSPACE/imgui-native-android/libimgui-java64.so
-                
+          
       - name: build mod
         run: |
           chmod +x ./gradlew
